//
//  SOXKeys_BitcoinDE.h
//  BitcoinApp
//
//  Created by Peter Hauke on 21.03.17.
//  Copyright © 2017 2sox / Peter Hauke. All rights reserved.
//

#import <Foundation/Foundation.h>

@interface SOXKeys_BitcoinDE : NSObject

#pragma mark - Notifications
FOUNDATION_EXPORT NSString *const SOXAPIKeysAndSecretsDidChangeNotification;
FOUNDATION_EXPORT NSString *const SOXOpenPreferenceKeyAndSecretNotification;

FOUNDATION_EXPORT NSString *const BitcoinDE_Notification_RequestShowAccountInfo;
FOUNDATION_EXPORT NSString *const BitcoinDE_Notification_RequestShowRates;
FOUNDATION_EXPORT NSString *const BitcoinDE_Notification_PresentBannerInformationForCurrency;

#pragma mark - Bitcoin flavours
FOUNDATION_EXPORT NSString *const BitcoinDE_TradingPair_BitcoinOriginal;
FOUNDATION_EXPORT NSString *const BitcoinDE_TradingPair_BitcoinCash;
FOUNDATION_EXPORT NSString *const BitcoinDE_TradingPair_Ethereum;

#pragma mark - BitcoinDE_ExecuteTrade
FOUNDATION_EXPORT NSString *const BitcoinDE_ExecuteTrade_OrderID;
FOUNDATION_EXPORT NSString *const BitcoinDE_ExecuteTrade_Type;
FOUNDATION_EXPORT NSString *const BitcoinDE_ExecuteTrade_BitcoinAmount;
FOUNDATION_EXPORT NSString *const BitcoinDE_ExecuteTrade_IsAutomaticTrade;
FOUNDATION_EXPORT NSString *const BitcoinDE_ExecuteTrade_Price;
FOUNDATION_EXPORT NSString *const BitcoinDE_ExecuteTrade_AutomaticTradePrice;

#pragma mark - BitcoinDE_ShowAccountInfo
FOUNDATION_EXPORT NSString *const BitcoinDE_ShowAccountInfo_MainKey;
#pragma mark | BTC-Balance
FOUNDATION_EXPORT NSString *const BitcoinDE_ShowAccountInfo_Balances;
FOUNDATION_EXPORT NSString *const BitcoinDE_ShowAccountInfo_Balance_total_amount;
FOUNDATION_EXPORT NSString *const BitcoinDE_ShowAccountInfo_Balance_available_amount;
FOUNDATION_EXPORT NSString *const BitcoinDE_ShowAccountInfo_Balance_reserved_amount;

#pragma mark | Fidor-Reservation
FOUNDATION_EXPORT NSString *const BitcoinDE_ShowAccountInfoFidorReservation_fidor_reservation;
FOUNDATION_EXPORT NSString *const BitcoinDE_ShowAccountInfoFidorReservation_total_amount;
FOUNDATION_EXPORT NSString *const BitcoinDE_ShowAccountInfoFidorReservation_available_amount;
FOUNDATION_EXPORT NSString *const BitcoinDE_ShowAccountInfoFidorReservation_reserved_at;
FOUNDATION_EXPORT NSString *const BitcoinDE_ShowAccountInfoFidorReservation_valid_until;
FOUNDATION_EXPORT NSString *const BitcoinDE_ShowAccountInfoFidorReservation_allocation;
FOUNDATION_EXPORT NSString *const BitcoinDE_ShowAccountInfoFidorReservation_allocation_percent;
FOUNDATION_EXPORT NSString *const BitcoinDE_ShowAccountInfoFidorReservation_allocation_max_eur_volume;
FOUNDATION_EXPORT NSString *const BitcoinDE_ShowAccountInfoFidorReservation_allocation_eur_volume_open_orders;

#pragma mark | Encrypted-Information
FOUNDATION_EXPORT NSString *const BitcoinDE_ShowAccountInfoEncryptedInformation_encrypted_information;
FOUNDATION_EXPORT NSString *const BitcoinDE_ShowAccountInfoEncryptedInformation_bic_short;
FOUNDATION_EXPORT NSString *const BitcoinDE_ShowAccountInfoEncryptedInformation_bic_full;
FOUNDATION_EXPORT NSString *const BitcoinDE_ShowAccountInfoEncryptedInformation_uid;

#pragma mark - BitcoinDE_ShowAccountLedger
#pragma mark | Details zur Position
FOUNDATION_EXPORT NSString *const BitcoinDE_ShowAccountLedger_Main;
FOUNDATION_EXPORT NSString *const BitcoinDE_ShowAccountLedger_Date;
FOUNDATION_EXPORT NSString *const BitcoinDE_ShowAccountLedger_Type;
FOUNDATION_EXPORT NSString *const BitcoinDE_ShowAccountLedger_Reference;
FOUNDATION_EXPORT NSString *const BitcoinDE_ShowAccountLedger_Cashflow;
FOUNDATION_EXPORT NSString *const BitcoinDE_ShowAccountLedger_Balance;

#pragma mark |- Tradedetails
FOUNDATION_EXPORT NSString *const BitcoinDE_ShowAccountLedger_Trade;
FOUNDATION_EXPORT NSString *const BitcoinDE_ShowAccountLedger_Trade_TradeID;
FOUNDATION_EXPORT NSString *const BitcoinDE_ShowAccountLedger_Trade_Price;
FOUNDATION_EXPORT NSString *const BitcoinDE_ShowAccountLedger_Trading_Pair;
//APIv4:
FOUNDATION_EXPORT NSString *const BitcoinDE_ShowAccountLedger_Trade_Currency_To_Trade;
FOUNDATION_EXPORT NSString *const BitcoinDE_ShowAccountLedger_Trade_Currency_To_Pay;
FOUNDATION_EXPORT NSString *const BitcoinDE_ShowAccountLedger_Trade_Currency;
FOUNDATION_EXPORT NSString *const BitcoinDE_ShowAccountLedger_Trade_Before_fee;
FOUNDATION_EXPORT NSString *const BitcoinDE_ShowAccountLedger_Trade_After_fee;


#pragma mark |- Page Details
FOUNDATION_EXPORT NSString *const BitcoinDE_ShowAccountLedger_Page;
FOUNDATION_EXPORT NSString *const BitcoinDE_ShowAccountLedger_Page_Current;
FOUNDATION_EXPORT NSString *const BitcoinDE_ShowAccountLedger_Page_Last;


#pragma mark - BitcoinDE_ShowMyOrders
FOUNDATION_EXPORT NSString *const BitcoinDE_ShowMyOrders_MainKey;

#pragma mark | Order Details
FOUNDATION_EXPORT NSString *const BitcoinDE_ShowMyOrders_OrderID;
FOUNDATION_EXPORT NSString *const BitcoinDE_ShowMyOrders_Type;
FOUNDATION_EXPORT NSString *const BitcoinDE_ShowMyOrders_MaxAmount;
FOUNDATION_EXPORT NSString *const BitcoinDE_ShowMyOrders_MinAmount;
FOUNDATION_EXPORT NSString *const BitcoinDE_ShowMyOrders_Price;
FOUNDATION_EXPORT NSString *const BitcoinDE_ShowMyOrders_MaxVolume;
FOUNDATION_EXPORT NSString *const BitcoinDE_ShowMyOrders_MinVolume;
FOUNDATION_EXPORT NSString *const BitcoinDE_ShowMyOrders_CreatedAt;
FOUNDATION_EXPORT NSString *const BitcoinDE_ShowMyOrders_EndDateTime;
FOUNDATION_EXPORT NSString *const BitcoinDE_ShowMyOrders_NewOrderForRemainingAmount;
FOUNDATION_EXPORT NSString *const BitcoinDE_ShowMyOrders_State;

#pragma mark | Order Requirements
FOUNDATION_EXPORT NSString *const BitcoinDE_ShowMyOrders_OrderRequirements;
FOUNDATION_EXPORT NSString *const BitcoinDE_ShowMyOrders_OrderRequirements_MinTrustLevel;
FOUNDATION_EXPORT NSString *const BitcoinDE_ShowMyOrders_OrderRequirements_OnlyKYCFull;
FOUNDATION_EXPORT NSString *const BitcoinDE_ShowMyOrders_OrderRequirements_PaymentOption;
FOUNDATION_EXPORT NSString *const BitcoinDE_ShowMyOrders_OrderRequirements_SeatOfBank;

#pragma mark | Page information
FOUNDATION_EXPORT NSString *const BitcoinDE_ShowMyOrders_Page;
FOUNDATION_EXPORT NSString *const BitcoinDE_ShowMyOrders_Page_Current;
FOUNDATION_EXPORT NSString *const BitcoinDE_ShowMyOrders_Page_Last;

#pragma mark - BitcoinDE_ShowMyTrades
#pragma mark | Trades
FOUNDATION_EXPORT NSString *const BitcoinDE_ShowMyTrades_Trades_MainKey;
FOUNDATION_EXPORT NSString *const BitcoinDE_ShowMyTrades_TradeID;
FOUNDATION_EXPORT NSString *const BitcoinDE_ShowMyTrades_Type;
FOUNDATION_EXPORT NSString *const BitcoinDE_ShowMyTrades_Price;
FOUNDATION_EXPORT NSString *const BitcoinDE_ShowMyTrades_Amount_Currency_To_Trade; // coin amount
FOUNDATION_EXPORT NSString *const BitcoinDE_ShowMyTrades_Amount_Currency_To_Trade_After_Fee; // coin amount - coin fee
FOUNDATION_EXPORT NSString *const BitcoinDE_ShowMyTrades_Fee_Currency_To_Trade; // coin fee
FOUNDATION_EXPORT NSString *const BitcoinDE_ShowMyTrades_Volume_Currency_To_Pay; // euro volume
FOUNDATION_EXPORT NSString *const BitcoinDE_ShowMyTrades_Volume_Currency_To_Pay_After_Fee; // euro volume - euro fee
FOUNDATION_EXPORT NSString *const BitcoinDE_ShowMyTrades_Fee_Currency_To_Pay; // euro fee
FOUNDATION_EXPORT NSString *const BitcoinDE_ShowMyTrades_NewOrderIDForRemainingAmount;
FOUNDATION_EXPORT NSString *const BitcoinDE_ShowMyTrades_State;
FOUNDATION_EXPORT NSString *const BitcoinDE_ShowMyTrades_MyRatingForTradingPartner;
FOUNDATION_EXPORT NSString *const BitcoinDE_ShowMyTrades_CreatedAt;
FOUNDATION_EXPORT NSString *const BitcoinDE_ShowMyTrades_SuccessfullyFinishedAt;
FOUNDATION_EXPORT NSString *const BitcoinDE_ShowMyTrades_CancelledAt;
FOUNDATION_EXPORT NSString *const BitcoinDE_ShowMyTrades_PaymentMethod;
FOUNDATION_EXPORT NSString *const BitcoinDE_ShowMyTrades_TradingPair;

FOUNDATION_EXPORT NSString *const BitcoinDE_ShowMyTrades_TradingPartnerInformation;
FOUNDATION_EXPORT NSString *const BitcoinDE_ShowMyTrades_TradingPartnerInformation_Username;
FOUNDATION_EXPORT NSString *const BitcoinDE_ShowMyTrades_TradingPartnerInformation_IsKYCFull;
FOUNDATION_EXPORT NSString *const BitcoinDE_ShowMyTrades_TradingPartnerInformation_TrustLevel;
FOUNDATION_EXPORT NSString *const BitcoinDE_ShowMyTrades_TradingPartnerInformation_BankName;
FOUNDATION_EXPORT NSString *const BitcoinDE_ShowMyTrades_TradingPartnerInformation_BIC;
FOUNDATION_EXPORT NSString *const BitcoinDE_ShowMyTrades_TradingPartnerInformation_SeatOfBank;
FOUNDATION_EXPORT NSString *const BitcoinDE_ShowMyTrades_TradingPartnerInformation_AmountTrades;
FOUNDATION_EXPORT NSString *const BitcoinDE_ShowMyTrades_TradingPartnerInformation_Rating;

#pragma mark | Page information
FOUNDATION_EXPORT NSString *const BitcoinDE_ShowMyTrades_Page;
FOUNDATION_EXPORT NSString *const BitcoinDE_ShowMyTrades_Page_Current;
FOUNDATION_EXPORT NSString *const BitcoinDE_ShowMyTrades_Page_Last;

#pragma mark - BitcoinDE_ShowOrderbook
FOUNDATION_EXPORT NSString *const BitcoinDE_ShowOrderbook_MainKey;

#pragma mark | Order
FOUNDATION_EXPORT NSString *const BitcoinDE_ShowOrderbook_OrderID;
FOUNDATION_EXPORT NSString *const BitcoinDE_ShowOrderbook_Type;
FOUNDATION_EXPORT NSString *const BitcoinDE_ShowOrderbook_TradingPair;
FOUNDATION_EXPORT NSString *const BitcoinDE_ShowOrderbook_MaxAmount;
FOUNDATION_EXPORT NSString *const BitcoinDE_ShowOrderbook_MinAmount;
FOUNDATION_EXPORT NSString *const BitcoinDE_ShowOrderbook_Price;
FOUNDATION_EXPORT NSString *const BitcoinDE_ShowOrderbook_MaxVolume;
FOUNDATION_EXPORT NSString *const BitcoinDE_ShowOrderbook_MinVolume;
FOUNDATION_EXPORT NSString *const BitcoinDE_ShowOrderbook_OrderRequirementsFullfilled;

#pragma mark | Trading Partner Information
FOUNDATION_EXPORT NSString *const BitcoinDE_ShowOrderbook_TradingPartnerInformation;
FOUNDATION_EXPORT NSString *const BitcoinDE_ShowOrderbook_TradingPartnerInformation_Username;
FOUNDATION_EXPORT NSString *const BitcoinDE_ShowOrderbook_TradingPartnerInformation_IsKYCFull;
FOUNDATION_EXPORT NSString *const BitcoinDE_ShowOrderbook_TradingPartnerInformation_TrustLevel;
FOUNDATION_EXPORT NSString *const BitcoinDE_ShowOrderbook_TradingPartnerInformation_BankName;
FOUNDATION_EXPORT NSString *const BitcoinDE_ShowOrderbook_TradingPartnerInformation_BIC;
FOUNDATION_EXPORT NSString *const BitcoinDE_ShowOrderbook_TradingPartnerInformation_Rating;
FOUNDATION_EXPORT NSString *const BitcoinDE_ShowOrderbook_TradingPartnerInformation_AmountTrades;

#pragma mark | Order Requirements
FOUNDATION_EXPORT NSString *const BitcoinDE_ShowOrderbook_OrderRequirements;
FOUNDATION_EXPORT NSString *const BitcoinDE_ShowOrderbook_OrderRequirements_MinTrustLevel;
FOUNDATION_EXPORT NSString *const BitcoinDE_ShowOrderbook_OrderRequirements_OnlyKYCFull;
FOUNDATION_EXPORT NSString *const BitcoinDE_ShowOrderbook_OrderRequirements_SeatOfBank;
FOUNDATION_EXPORT NSString *const BitcoinDE_ShowOrderbook_OrderRequirements_PaymentOptions;

#pragma mark - BitcoinDE_ShowRates
FOUNDATION_EXPORT NSString *const BitcoinDE_ShowRates_MainKey;
#pragma mark | Rates
FOUNDATION_EXPORT NSString *const BitcoinDE_ShowRates_rate_trading_pair;
FOUNDATION_EXPORT NSString *const BitcoinDE_ShowRates_rate_weighted;
FOUNDATION_EXPORT NSString *const BitcoinDE_ShowRates_rate_weighted_3h;
FOUNDATION_EXPORT NSString *const BitcoinDE_ShowRates_rate_weighted_12h;

#pragma mark - WebSocket
FOUNDATION_EXPORT NSString *const BitcoinDE_WebSocket_AddOrder_MainKey;
FOUNDATION_EXPORT NSString *const BitcoinDE_WebSocket_RemoveOrder_MainKey;
FOUNDATION_EXPORT NSString *const BitcoinDE_WebSocket_UpdateOrder_MainKey;

FOUNDATION_EXPORT NSString *const BitcoinDE_WebSocket_BuyOrderType;
FOUNDATION_EXPORT NSString *const BitcoinDE_WebSocket_SellOrderType;
FOUNDATION_EXPORT NSString *const BitcoinDE_WebSocket_TradingPair;

#pragma mark | Add_Order
FOUNDATION_EXPORT NSString *const BitcoinDE_WebSocket_AddOrder_OrderID;
FOUNDATION_EXPORT NSString *const BitcoinDE_WebSocket_AddOrder_SocketObjectID;
FOUNDATION_EXPORT NSString *const BitcoinDE_WebSocket_AddOrder_OrderType;
FOUNDATION_EXPORT NSString *const BitcoinDE_WebSocket_AddOrder_Amount;
FOUNDATION_EXPORT NSString *const BitcoinDE_WebSocket_AddOrder_MinAmount;
FOUNDATION_EXPORT NSString *const BitcoinDE_WebSocket_AddOrder_Price;
FOUNDATION_EXPORT NSString *const BitcoinDE_WebSocket_AddOrder_MinTustLevel;
FOUNDATION_EXPORT NSString *const BitcoinDE_WebSocket_AddOrder_OnlyKYCFull;
FOUNDATION_EXPORT NSString *const BitcoinDE_WebSocket_AddOrder_IsKYCFull;
FOUNDATION_EXPORT NSString *const BitcoinDE_WebSocket_AddOrder_SeatOfBankOfCreator;
FOUNDATION_EXPORT NSString *const BitcoinDE_WebSocket_AddOrder_BICShort;
FOUNDATION_EXPORT NSString *const BitcoinDE_WebSocket_AddOrder_BICFull;
FOUNDATION_EXPORT NSString *const BitcoinDE_WebSocket_AddOrder_TradeOfSepaCountry;
FOUNDATION_EXPORT NSString *const BitcoinDE_WebSocket_AddOrder_PaymentOption;

#pragma mark | Remove_Order
FOUNDATION_EXPORT NSString *const BitcoinDE_WebSocket_RemoveOrder_OrderID;
FOUNDATION_EXPORT NSString *const BitcoinDE_WebSocket_RemoveOrder_OrderType;
FOUNDATION_EXPORT NSString *const BitcoinDE_WebSocket_RemoveOrder_Amount;
FOUNDATION_EXPORT NSString *const BitcoinDE_WebSocket_RemoveOrder_Price;

#pragma mark | Update_Order

@end
